### ISSUE TITLE
Make a codesandbox example

### ISSUE THREAD

**Issue by artokun** [beyonk-adventures/svelte-carousel#29]
This would be much better with a link to a codesandbox so we can quickly see it and decide to use it or now. Definitely boosts star count.

**Comment by antony** [comment]
@artokun Surely I'd demo it in the Svelte REPL :) https://svelte.dev/repl/3953567d530b41d087ab7eaa8e7e632a?version=3.22.3

I'm not too bothered about the star count on this project, since I don't think carousels are a great solution to any problem.

I'll add it to the README. Feel free to improve it.
