### ISSUE TITLE
Cannot set a 'current' slide index less than 2.

### ISSUE THREAD

**Issue by antony** [beyonk-adventures/svelte-carousel#3]
Not sure why but I've just noticed this. Needs some investigation.

**Comment by DanielSokil** [comment]
This bug is coming from `requiredSeat` constant in the `oncreate` method. When setting `current` to 1, requiredSeat is equal to -1, and then `newSeat.style.order` is trying to set 1 on undefined, in the `setNewSeatOrder` method.

I can't quite figure out what your intention is in the `requiredSeat` algorithim.

**Comment by antony** [comment]
@DanielSokil it wasn't really my algorithm - it comes from the original codepen I based the carousel on, but   I remember a skew of -1 on the numbers, since I believe the last slide becomes the first, in case you wanted to go backwards as your first move.

However - thanks for this bit of sleuthing, it should make it quite trivial to fix!
